### ISSUE TITLE
Deactivating, deleting and reactivating the same host fails

### ISSUE THREAD

**Issue by cglewis** [rancherio/rancher#1022] opened 2015-06-03 16:29 UTC
I deactivated a host and then deleted it from the UI.  It went away and stopped the agent on the host (as expected).  When I tried to reactivate the host with a new agent container it happily did it's thing with no errors or warnings, but never showed up in the UI.

I found that if I poked around with the URLs, the old one still existed in a purged state, which I assume is why it's failing.  It should reactivate when the new agent registering the host comes up.  Running agent 0.7.9 and rancher 0.23.0-rc1.

![screen shot 2015-06-03 at 9 25 24 am](https://cloud.githubusercontent.com/assets/2931079/7965502/c9e84fc2-09d2-11e5-8f83-c642a6a99b9e.png)

**Comment by deniseschannon** [comment] 2015-06-03 16:33
This is a duplicate of #225. There is a workaround in the notes, but we are looking to fix it.

**Closed by deniseschannon** 2015-06-03 16:33 UTC
