### ISSUE TITLE
[add container] fields 'command' and 'user' are dirty after being touched

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#177] opened 2015-03-09 17:45 UTC
If you start a simple ubuntu image and click the user field, but not put anything, the example text is put back ("e.g. apache"). But starting container fails: "Invalid user". It seems the field is dirty. 
Same goes for command field.

**Comment by ibuildthecloud** [comment] 2015-03-09 18:24
@vincent99

**Comment by vincent99** [comment] 2015-03-31 19:46
Yes.. this is pretty much a duplicate of #96 and #239 in general so we will track it there.

**Closed by vincent99** 2015-03-31 19:46 UTC
Labels: bug
