### ISSUE TITLE
Rancher-agent reconnecting

### ISSUE THREAD

**Issue by bnoon** [rancherio/rancher#1412] opened 2015-07-07 13:23 UTC
When adding a new custom host (ubuntu, docker 1.7) to an existing rancher server (on rancheros v0.3.3 rancher server v0.25) I am getting the following python exception:

```
2015-07-07 13:17:30,890 ERROR agent [140532250850640] [event.py:108] c816a4ee-0b5e-45c7-a404-4707fc48a935 : Unknown error 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 97, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 112, in _add_instances
    self.add_container('running', container, containers)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 123, in add_container
    'uuid': self._get_uuid(container),
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 157, in _get_uuid
    uuid = container['Labels']['io.rancher.container.uuid']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
In the UI, the host is looping through active / disconnected.  Any thoughts?

**Comment by deniseschannon** [comment] 2015-07-08 21:56
This is a duplicate of https://github.com/rancherio/rancher/issues/1147. 

There are some scenarios where `labels` will be null on a container. We have created a fix that will no longer assume that `labels` will exist. This should come out in our next release.

**Closed by deniseschannon** 2015-07-08 21:56 UTC
