### ISSUE TITLE
List containers on host details screen alphabetically (and force Rancher agents to the bottom)

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#467] opened 2015-04-07 20:36 UTC
Version: Build from Master (4/7/15)

When we look at the detailed host page and look at the containers in the host, the containers are listed by creation time.

Can we update so that it's alphabetical? Also, can we make sure the Rancher agents (Network Agent, LB Agent, Cluster Server (i.e. SWARM Container)) are at the bottom. When a host has an extremely high number of containers, this sorting will be helpful.

![screen shot 2015-04-07 at 1 36 05 pm](https://cloud.githubusercontent.com/assets/11410997/7032942/249cbe64-dd2b-11e4-8cf3-be9bef8334ad.png)

**Comment by vincent99** [comment] 2015-04-23 01:20
Duplicate of #354

**Closed** 2015-04-23 17:55 UTC
Labels: area/container, area/host, area/ui, enhancement, status/duplicate
