### ISSUE TITLE
Error while creating a project

### ISSUE THREAD

**Issue by lalyos** [rancherio/rancher#385] opened 2015-03-31 20:34 UTC
I've created a 5 node racher cluster on GCE. i am able to start containers, but when i try to create a project, it fails, see logs:

https://gist.github.com/lalyos/e2de8cc11b6a71a63499

btw: #ranchermeetup was awesome!

**Comment by vincent99** [comment] 2015-03-31 21:58
@hibooboo2 Can you look at @lalyos NPE stacktrace and fix the cause in the updated projects release?  GitHub has been getting DDOSed for days so it's likely related to failing to connect to them.

**Comment by vincent99** [comment] 2015-04-20 03:50
Ping @hibooboo2

**Comment by vincent99** [comment] 2015-04-23 05:04
@lalyos can you try again with v0.17?  We've significantly changed how projects work.

**Comment by hibooboo2** [comment] 2015-05-04 19:21
@lalyos I believe this is fixed with the new projects. Patch. This was due to improper management of errors.

**Closed by hibooboo2** 2015-05-04 19:21 UTC
Labels: area/project, bug, question
