### ISSUE TITLE
create a custom host, but host page display "No hosts or containers yet".

### ISSUE THREAD

**Issue by cnzg** [rancherio/rancher#1039] opened 2015-06-04 11:39 UTC
![rancher_issue_1](https://cloud.githubusercontent.com/assets/12028743/7983289/57384a5c-0af1-11e5-86ef-63156646810d.png)

**Comment by deniseschannon** [comment] 2015-06-04 16:34
When you launch a custom host on the same VM as rancher server, you'll need to add a `-e CATTLE_AGENT_IP=<ip_of_server> into the custom command in order for it to work. 

it's documented in the wiki, but not very clear in the UI. Kind of duplicate of #872.

Please re-open if the workaround doesn't work for you.

**Closed by deniseschannon** 2015-06-04 16:34 UTC
Labels: status/duplicate
