### ISSUE TITLE
Environments (projects API) doesn't delete resources when environment is deleted

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#984] opened 2015-05-29 21:32 UTC
v0.22.1-rc2

Steps to Reproduce
1. Create an environment
2. Launch a DigitalOcean machine using the UI
3. Delete the environment

Result: the Digital Ocean machine still exists in DO.

Expected Result: Since we created the machine through Rancher, we should be deleting the machine as well.

**Comment by hibooboo2** [comment] 2015-05-29 22:58
Duplicate of rancherio/rancher#340

**Closed by hibooboo2** 2015-05-29 22:58 UTC
Labels: area/environment, bug, status/duplicate
