### ISSUE TITLE
[API] - Not able to list projects when using API keys of admin/project.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#272] opened 2015-03-19 19:18 UTC
Version - V0.12.0

Create a project.
Generate API keys for the project.
Generate API keys for the "Default" project.

When trying to list project with any one of these API keys, we get an "Internal Server Error".

http://<ipaddress>:8080/v1/projects

{
"id": "838bce24-a7ff-4e44-90a2-6d9fa553661f",
"type": "error",
"links": { },
"actions": { },
"status": 500,
"code": "Internal Server Error",
"message": "Internal Server Error",
"detail": null,
}

**Comment by hibooboo2** [comment] 2015-03-19 19:21
This is not a bug.
This is by design.

**Comment by hibooboo2** [comment] 2015-03-19 19:42
Currently you cannot list projects because in order to find out what projects you have access too you must be authenticated through github so that you can compare externalIds However api keys are authentication via cattle not github.

I know of a way to add this functionality but currently we do not plan on supporting it.

**Comment by vincent99** [comment] 2015-04-23 06:19
Discussed with @ibuildthecloud a while ago and we're wontfix for now, we'd have to store (and care for and feed) the user's github access token to do this.

**Closed by vincent99** 2015-04-23 06:19 UTC
Labels: area/api, area/project, kind/enhancement, status/wontfix
