### ISSUE TITLE
Creating a container with managed networking

### ISSUE THREAD

**Issue by 5an1ty** [rancherio/rancher#1188] opened 2015-06-12 09:33 UTC
When I create container with managed networking for example based on the nginx. The container creation process seems to be stuck at the networking step. I think my networking container seems to be having issues.

When I create the same container with networking set to host it immediately pops up...

I tried looking for logs but I can't see any log message for the period that I create that container.

I first tried with rancher/server:latest but I have the same issue with rancher/server:v0.24.0-rc2

Edit: running on a machine that runs both host and agent. With usage of:
```-e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER>```

Edit2: Seems like the network agent is throwing a bunch of errors

Edit3: Ok seems like the root cause is that the network agent can not access the external network. It can ping my host but it can't ping google.com.

Edit4: Did a setup of 2 rancheros instances one server one host and everything works immediately as it should. So this is definitely still a server and agent on same machine issue.

**Comment by deniseschannon** [comment] 2015-06-12 21:17
I did the same set up as you. Using RancherOS instance, run rancher/server, use the same server host to add the rancher agent. I have no issues launching nginx on the managed network.

Did you make any networking changes to RancherOS? I'm also using the GCE image of RancherOS v0.3.1. 

How are you starting RancherOS?

**Comment by 5an1ty** [comment] 2015-06-13 09:13
@deniseschannon sorry, I wasn't clear, the setup I'm experimenting with is agent and server on elementary os (based on ubuntu). The rancher os I mentioned was a separate setup with 2 machines one for server and one for agent and that one is working as intended.

On the single machine setup I already tried removing and reinstalling rancher multiple times to get it working but every time the same behavior as explained in the OP. There might be something messed up in the networking part but I flushed allmost everything there was in my iptables before reinstall so I guess that should be fine?

**Comment by deniseschannon** [comment] 2015-06-17 16:26
@5an1ty With the recent release of our Beta product, we've made a lot of improvements to the product in the last week. Could you try to use that version? It's v0.24.0 and currently tagged as our latest. Since you're using an elementary OS, I'm not sure what could be the issue.

Here are a couple of options to try:

Try setting up with 2 of your elementary OS boxes (ideally fresh setup so that iptables are clear) to see if you can create a container with the managed network. This would potentially help pinpoint whether it's the OS networking or not. If this doesn't work, then it might be something related to the networking your OS.

If the above works, try again with using 1 machine for the server and agent and adding in the `-e CATTLE_AGENT_IP=<server_IP>`.  Again, it'd be best if you could use a fresh setup and grab the latest.

**Comment by deniseschannon** [comment] 2015-07-02 16:43
@5an1ty if you get a chance to test this out using our new latest (v0.25.0) and run into the same issues, please re-open. I haven't been able to reproduce this issue and will close it for now. 

I believe your version did have some dns issues, so the latest versions should fix your issue.

**Closed by deniseschannon** 2015-07-02 16:43 UTC
