### ISSUE TITLE
removing host after deleting containers can hang in removing state on server

### ISSUE THREAD

**Issue by hrwebasst** [rancherio/rancher#1172] opened 2015-06-11 22:33 UTC
Server v24-rc2
agent was having issues, removed all containers on host and /var/lib/rancher/state then removed from interface and stuck in removing state.

![screenshot54](https://cloud.githubusercontent.com/assets/9060082/8119976/049f0520-104f-11e5-9941-d98f74f5eda2.png)

The one on the far right is the host re-added after removal.

![screenshot55](https://cloud.githubusercontent.com/assets/9060082/8120010/5e686bbe-104f-11e5-8571-30289a0dc463.png)

**Comment by hrwebasst** [comment] 2015-06-11 22:34
For reference Network agent is in progress of deleting

**Comment by deniseschannon** [comment] 2015-06-12 18:50
Was the network agent or the Rancher agent having issues? 

Also, I'm thinking that changing /var/lib/rancher/state and then removing in the UI might cause the UI to be in stuck state. @vincent99 would need to confirm.

In v0.24.0-rc2, you can remove hosts and add them back to server with no issues. So you no longer need to change /var/lib/rancher/state.

**Comment by deniseschannon** [comment] 2015-06-15 16:59
Can you let me know if you see this issue again? Since we've eliminated the need to change the /var/lib/rancher/state, I think this shouldn't be reproduced.

**Comment by deniseschannon** [comment] 2015-06-24 21:49
I'm going to close this issue. Please re-open if you can reproduce without changing /var/lib/rancher/state.

**Closed by deniseschannon** 2015-06-24 21:49 UTC
