### ISSUE TITLE
[UX] Removing an item is inconsistent across the application

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#349] opened 2015-03-27 17:53 UTC
There should be some consistency with how and when Deactivate, Delete, Purge show and work across the application.

For Machine/Host and Registry you have to deactivate, delete then purge (which seem a lot of steps to remove)
For Projects and Containers you have just delete (which automatically purges for you at point in future), although if you restore before the purge you have to reactivate the project.

This is very confusing.  I suggest we don't show anything after delete (even if we are keeping it in background before purge).  Also we should be consistent with deactivate, either show for all or none.

**Comment by vincent99** [comment] 2015-04-23 05:11
I think we can call this a (pre-)duplicate of #384, which addresses the need to deactivate before delete, and delete vs purge.

**Closed** 2015-04-23 05:11 UTC
Labels: area/none, kind/enhancement
