### ISSUE TITLE
No ports mapped when creating an environment

### ISSUE THREAD

**Issue by cglewis** [rancherio/rancher#925] opened 2015-05-26 16:25 UTC
If I click the `+` on port map for an environment, and choose the private port (on the container) and check publish all ports to a random host port, when the container is started in the environment is says there are no port mappings.  This is not a problem if I do the same thing as a single container on a specific host from the `hosts` page.

**Comment by deniseschannon** [comment] 2015-06-02 21:25
@cglewis This looks like a duplicate of https://github.com/rancherio/rancher/issues/589 and the comments seem to indicate that this shouldnt' be available for services. I just wanted to confirm that we're talking about the same.

**Comment by deniseschannon** [comment] 2015-06-02 21:26
@will-chan it looks as if we are planning to hide the "publish all ports" for services.

**Comment by cglewis** [comment] 2015-06-02 22:01
@deniseschannon yes that is correct, thanks.

**Comment by deniseschannon** [comment] 2015-06-02 22:04
I'm going to close this issue in favor of #589.

**Closed by deniseschannon** 2015-06-02 22:04 UTC
Labels: area/service, bug
