### ISSUE TITLE
API secret key shown in clear text in UI when trying to edit api keys.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1165] opened 2015-06-11 20:21 UTC
Server version - built from master - jun/11

From list view of "API & keys" , click on "Edit" option to launch the "Edit API key" option.
password is presented in clear text.

![screen shot 2015-06-11 at 1 16 37 pm](https://cloud.githubusercontent.com/assets/4266958/8117333/3294a966-103c-11e5-801e-c4e6ad041e7b.png)

**Comment by vincent99** [comment] 2015-06-11 21:11
Duplicate of #209.

**Closed by vincent99** 2015-06-11 21:11 UTC
Labels: area/ui, bug
