### ISSUE TITLE
[UI][LB] Delete target overlay is showing ID instead of Name

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#529] opened 2015-04-16 19:16 UTC
v0.16.0
Steps:
1.  Create LB
2.  Go to LB info page
3.  Click on Targets
4.  Remove Target

Results:
The delete overlay is showing the Target id instead of the name

Expected:
Should show name

**Comment by vincent99** [comment] 2015-04-16 22:24
Dupe of #461.

**Closed by vincent99** 2015-04-16 22:24 UTC
Labels: bug, duplicate
