### ISSUE TITLE
Links across hosts not working?

### ISSUE THREAD

**Issue by clemenko** [rancherio/rancher#892] opened 2015-05-22 14:17 UTC
I am trying to deploy several web servers within a service description and link them to a redis "service". It appears that it is not working. It even appears that if I use the Managed network for a container the link function is not working. I have validated it using the docker commands on 1 host. 

docker 1.6.2
rancher/server:v0.21.3

**Comment by deniseschannon** [comment] 2015-05-22 21:56
Are you using Ubuntu? https://github.com/rancherio/rancher/issues/893 was logged earlier today, but I didn't see the same issues in CentOS/RHEL 7.

**Comment by clemenko** [comment] 2015-05-23 11:36
Sorry Centos 7. Looks like #893  is the same issue. close this one..

**Comment by deniseschannon** [comment] 2015-05-23 19:40
Dupiclate of #893, but on CentOS 7.

**Comment by deniseschannon** [comment] 2015-05-26 16:34
I'm re-opening as it's fixed for Ubuntu. @clemenko can you test this out with v0.22.0-rc1 since you love the bleeding edge. :) i never had the issue with my centos 7 setup so unable to reproduce.

**Comment by deniseschannon** [comment] 2015-05-26 17:20
@clemenko are you reusing your CentOS 7 hosts and just launching new server and agent containers? If I launch new CentOS 7 hosts and add containers, I have no issues. But I'm having issues when I reuse my CentOS 7 setup from testing a previous version. Basically, when I stopped my old rancher server and agents and ran new docker commands, my containers on my hosts cannot ping each other.

**Comment by clemenko** [comment] 2015-05-26 17:21
I am build new servers every time. Let me test with v0.22.0-rc1 tonight.

**Comment by clemenko** [comment] 2015-05-26 23:00
Just tested. My setup is all updated centos 7 with docker 1.6.2. I am using the docker.io/clemenko/demo_app1 which looks for a "link" called redis.  I found that it does work for nodes that aren't also running rancher-server. When running the server and the agent on the same box it picks up the ip of docker0 and not eth0/em0. See screenshot. [0]

Is running server and agent on the same host cool?

[0] https://www.dropbox.com/s/i3xjzeygpenc408/docker_ip.jpg?dl=0

**Comment by cloudnautique** [comment] 2015-05-26 23:15
@clemenko you can run the server and agent on the same host, you just have to add `-e CATTLE_AGENT_IP=<public ip>` to the command to start the agent. This tells it not to use the internal IP address that the other hosts can not reach. The other caveat is that you will not be able to run services with 8080 exposed.

**Comment by clemenko** [comment] 2015-05-27 00:16
@cloudnautique You might be misunderstanding. The server runs fine on the external IP. In the Rancher UI you can see that the agent is reporting the host on the docker0 ip. This appears to be a bug since v0.20.2. I will test to see which version this started appearing. I know this WAS working correctly.

**Comment by cloudnautique** [comment] 2015-05-27 04:14
@clemenko, sorry, I don't think I did a good job explaining. What you are seeing is a known behavior. When the rancher/agent container starts it tries to determine the IP of the host based on the interface it uses to talk to rancher/server. Since the agent and server are in containers on the same host, the agent reports the IP of docker0.

In order to change this behavior, when you launch the rancher/agent container based on the command from the UI, you need to add `-e CATTLE_AGENT_IP=<IP of the host>`. This tells the agent on startup to use that IP vs. auto-detecting an IP. The command ends up looking something like:

```
docker run -d --privileged -e CATTLE_AGENT_IP=XX.XX.XX.XX -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.8 http://<rancher>/<tokens>
```

Hopefully that is clearer.

**Comment by clemenko** [comment] 2015-05-27 11:22
@cloudnautique The problem is that this behavior was NOT present in previous versions of rancher server. Why does running the agent command work on several box EXCEPT on when the server is on the same box? I don't have to modify the command on the other servers.

Screenshot of the v0.22-rc1 : https://www.dropbox.com/s/b5ymerzn8lh0ayi/rancher_22_1.jpg?dl=0

Here is my build scripts : https://github.com/clemenko/tugboat-digitalocean-rancher

I tested the "latest" build of rancher server. When did this behavior change? Why does the auto-detecting of the ip fail on the server and not the basic agents?

Having to run a different agent command on the server adds unnecessary complexity. 

I just build it a setup with "rancher/server:latest". Then I used this command to start the agent on the server : 
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -e CATTLE_AGENT_IP=162.243.52.175 rancher/agent:v0.7.6 http://162.243.52.175:8080/v1/scripts/97E90BFE73010EB0AE62:1432724400000:XW6YFK0F9KY2M8NcE8xvZBEV8k


And I am STILL seeing the "web2" container on the server not being able to talk to "redis" container on the other host. 

Screenshot : https://www.dropbox.com/s/c8dvyc4snw9g77f/rancher_latest_1.jpg?dl=0

**Comment by clemenko** [comment] 2015-05-27 12:29
I can confirm that the addition of "-e CATTLE_AGENT_IP=162.243.52.175" works with one caveat. If you run docker agent command without the "-e CATTLE_AGENT_IP=162.243.52.175" it won't work if you stop the agent and restart it with the "-e"...

**Comment by deniseschannon** [comment] 2015-05-28 16:06
We've created a separate issue to add to the UI about adding an agent on the same host as rancher server. https://github.com/rancherio/rancher/issues/872

**Comment by deniseschannon** [comment] 2015-05-28 16:15
@clemenko Just to close on this loop, your links are working across hosts in the CentOS 7 setup? Can we close this issue?

**Comment by clemenko** [comment] 2015-05-28 16:17
Yes.. they are working. I was hitting the agent running on the wrong ip on the server issue. Close this.

**Closed** 2015-05-28 16:29 UTC
Labels: area/networking, bug
