### ISSUE TITLE
Getting 404 when I click on logs if container is created before any hosts

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#601] opened 2015-04-23 20:53 UTC
v0.17.0
Steps:
1.  Create a project
2.  Go to project
3.  Go to Containers page before adding any machine/hosts
4.  Add a container
5.  View Logs for newly created container

Results:
404 page

Expected:
Logs?

**Comment by vincent99** [comment] 2015-04-23 20:57
Duplicate of #212

**Closed by vincent99** 2015-04-23 20:57 UTC
Labels: area/container, area/ui, bug, status/duplicate
