### ISSUE TITLE
No validation that credentials are correct when adding Registry

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#418] opened 2015-04-02 21:53 UTC
v0.14.2

Steps:
1.  Go to Registries
2.  Add Registry
3.  Add a credential, but put in an invalid password

Results:
Registry is added and you don't know that your password is incorrect until you try to add a container using that credential and it fails.

Expected:
Validate credentials on create registry.

**Comment by vincent99** [comment] 2015-04-15 00:09
This is not trivial, will require API support.

**Comment by vincent99** [comment] 2015-05-12 07:31
Duplicate of #300.

**Closed by vincent99** 2015-05-12 07:31 UTC
Labels: area/registry, area/ui, enhancement
