### ISSUE TITLE
Project Description isn't shown anywhere

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#963] opened 2015-05-28 21:06 UTC
v0.22.1-rc2

Steps to Reproduce:

1. Create a project with a description.

Result: Can't find anywhere that displays the project's description.

Either remove the option of being able to add a description to a project or find a place to show the project description.

**Comment by vincent99** [comment] 2015-05-28 21:40
Dupe of https://github.com/rancherio/rancher/issues/555

**Closed by vincent99** 2015-05-28 21:40 UTC
Labels: area/ui
