### ISSUE TITLE
Version number should be given at the bottom of pages

### ISSUE THREAD

**Issue by faddat** [rancherio/rancher#1038] opened 2015-06-04 10:37 UTC
eg: Rancher Version x.x.x

It'd just make life simpler, that's all :).

**Comment by deniseschannon** [comment] 2015-06-04 16:30
Duplicate of #721. We need to get the version into the API first before it can be in the UI, but once in the API, we will plan on making it accessible in the UI.

**Closed by deniseschannon** 2015-06-04 16:30 UTC
