### ISSUE TITLE
The rancher agent isn't running but the UI show the host as active

### ISSUE THREAD

**Issue by Nicofuma** [rancherio/rancher#1082] opened 2015-06-08 08:33 UTC
Hi,

I have activated the rancher agent on my server it works for a few time and then the hosts disappear in the UI. I didn't have the time to investigate so I just let it like that.
Yesterday I had to kill it the hard way (see https://github.com/rancherio/rancher/issues/1081) and now the host is back in the UI and displayed as active even if the agent is not running, and obviously the UI doesn't show the reality but an old snapshot.

Like I said in the other ticket I grab all the logs if you want me to look at something.

**Comment by deniseschannon** [comment] 2015-06-08 16:51
The bug is a duplicate of #701. We're targeting to fix this in our Beta release.

As for the comment about the hosts disappearing in the UI, I'm not really sure why that would occur. Are you running the agent on the same host as server? If so, you'll need to add `-e CATTLE_AGENT_IP=<server_ip>` to the command in order for the rancher agent to pick up the right IP.  https://github.com/rancherio/rancher/issues/872

**Closed by deniseschannon** 2015-06-08 16:51 UTC
Labels: area/ui, bug
