### ISSUE TITLE
Docker Private Image "Not Found"

### ISSUE THREAD

**Issue by andrewmunsell** [rancherio/rancher#968] opened 2015-05-29 00:26 UTC
I have an account at the Docker Hub with some private Docker images under an organization. Even though I add my account to the "registries" section of the control panel, I am still having issues launching new services when the image is not already pulled to the machine. The error is an "image not found" error.

Pulling the image manually on the Docker host before creating the service causes the service to launch correctly.

**Comment by AnthonySendra** [comment] 2015-05-29 13:14
Same here.

**Comment by deniseschannon** [comment] 2015-05-29 15:49
What Rancher version are you using? And exactly how are you inputting image name? We don't document it clearly but the image name that you would use in `docker run` is the image name that would go in the space. 

The syntax should be something like this: 

`[docker]:[registry-name]/[namespace]/[imagename]:[version]`

**Comment by andrewmunsell** [comment] 2015-05-29 16:19
I'm using the latest version of Rancher that's been published to the Docker registry. The image name is simply "[myorganization]/dashboard", since it's located on the Docker Hub.

**Comment by hibooboo2** [comment] 2015-05-29 17:12
@andrewmunsell Could you please tell me what the CATTLE_RANCHER_SERVER_IMAGE environment variable is from within your rancher contianer.

**Comment by ibuildthecloud** [comment] 2015-05-29 17:28
@andrewmunsell you can find the CATTLE_RANCHER_SERVER_IMAGE env var from doing a "docker inspect" on your rancher/server container

**Comment by vincent99** [comment] 2015-06-01 05:02
I believe this is a (pre-)duplicate of #985.  Private registries are not working with services.

**Closed by vincent99** 2015-06-01 05:02 UTC

**Comment by cqcwillard** [comment] 2016-04-20 21:16
This issue still seems present with the latest release.  I'm having the same problem @andrewmunsell encountered, and it seems unrelated to #985.
