### ISSUE TITLE
State system requirements (ram/cpu)

### ISSUE THREAD

**Issue by basickarl** [rancherio/rancher#756] opened 2015-05-09 01:05 UTC
If you guys could please state the recommended system requirements in terms of cpu and ram that would be great, just spent half an hour trying to figure out why I couldn't log into rancher, was due to memory issues (wasn't expecting rancher to use so much ram).

**Comment by deniseschannon** [comment] 2015-05-14 16:16
@basickarl sorry about that! 

@ibuildthecloud what's the minimum system requirements that we could add to the README?

**Comment by deniseschannon** [comment] 2015-06-06 22:42
Duplicate of #617.

@basickarl We're hoping to get some official docs out in the next couple of weeks so we'll make sure to include that in the docs as well as the README.

**Closed by deniseschannon** 2015-06-06 22:42 UTC
Labels: area/documentation, enhancement
