### ISSUE TITLE
Error when starting Rancher

### ISSUE THREAD

**Issue by moimael** [rancherio/rancher#1376] opened 2015-07-01 14:02 UTC
I get some strange errors from time to time when starting Rancher:

```
time="2015-07-01T14:04:19Z" level=info msg="Starting go-machine-service..." gitcommit="9320efc" 
2015-07-01 14:04:31,757 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [12] count [1] 
2015-07-01 14:04:36,740 ERROR [:] [] [] [] [cutorService-21] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:13], exit code [1] output [nsenter: failed to execute /var/lib/cattle/events/config.update: No such file or directory
] 
2015-07-01 14:04:40,764 ERROR [:] [] [] [] [cutorService-25] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [configscripts, services, agent-instance-scripts, monit, agent-instance-startup] on [agent:13], exit code [1] output [nsenter: failed to execute /var/lib/cattle/events/config.update: No such file or directory
```

I also hit regularly this error :
```
time="2015-07-01T14:19:44Z" level=error msg="Unable to create EventRouter" Err="Get http://rancher.alinto.net/v1: dial tcp 83.145.109.239:80: no route to host" 
time="2015-07-01T14:19:44Z" level=info msg="Exiting go-machine-service..." 
```
It prevent Rancher from working completely.

**Comment by ibuildthecloud** [comment] 2015-07-01 15:40
Are you running the rancher/server on the same host as an agent?  What port do you have rancher/server listening on?  There's usually two reasons you see the dial error above.

1) Your server is in fact not listening on 83.145.109.239:80
2) You have stale iptables rules

For 1) if your host is a different ip:port then go to the UI and change the host registration setting in the upper right.

For 2) you need to reset the iptables.  Run 

    sudo iptables -F CATTLE_PREROUTING -t nat

2) happens when you run the agent and server on the same machine.  We don't quite have a fix for this yet.

**Comment by moimael** [comment] 2015-07-01 15:51
Yes I am, is it not recommended ? rancher/server listen on port 80 (I tried to put it behind an hipache or nginx proxy but it doesn't work completely)
1) I checked this it was listening
2) I might be this one, I'll check next time it happens, thanks for the fix :)

Hmm ok, we are a bit short on ipv4, that's why i didn't dedicate a whole machine to rancher/server, I might try with ipv6, how does rancher support it ?

Thanks !

**Comment by ibuildthecloud** [comment] 2015-07-02 17:11
No ipv6 support :(  I'd suggest you create an issue for ipv6.  If we get enough users asking for it we will prioritize it.  So far most people ask out of curiosity but no strong need.

Running agent on the same box as the server is fine, its supported but just sometimes odd things happening because it is like rancher is managing itself.  So for 2) the problem is that the iptables is stale, but rancher can't start to fix the iptables...

**Comment by deniseschannon** [comment] 2015-07-06 17:18
@moimael I created https://github.com/rancherio/rancher/issues/1403

I believe the rest of this issue has been solved, so I"ll close it. If not, please feel free to reopen.

**Closed by deniseschannon** 2015-07-06 17:18 UTC
