### ISSUE TITLE
Containers created with --rm are not removed automatically

### ISSUE THREAD

**Issue by dcardin** [rancherio/rancher#897] opened 2015-05-22 18:15 UTC
I would expect that containers created manually with the --rm option would be removed from the interface when the container dies.

**Comment by vincent99** [comment] 2015-05-22 23:15
Ping @cjellick

**Comment by cjellick** [comment] 2015-05-27 13:20
I cannot reproduce. The container is properly removed from Rancher when it dies and is removed on the host.

@dcardin are you still experiencing this problem? Is it possible that  you're using an older version of rancher? (Would have to be a few weeks old to not have this functionality).

**Comment by cjellick** [comment] 2015-05-27 17:10
Actually, I think I just fixed this yesterday. Here's the issue I created for it (not realizing it was the same as this issue):
https://github.com/rancherio/rancher/issues/934

**Comment by dcardin** [comment] 2015-06-01 15:05
We'll test it. Thanks for the heads up :)

**Comment by sangeethah** [comment] 2015-06-08 17:21
Tested with server version - V0.23.0-rc6 which is currently the latest

From host, Launched a containerusing the following command:
docker run --rm -it ubuntu bash

Container gets synced to be in "running" state in cattle server.

From host , Exit the container.

When rancher receives the events , container gets marked in "Destroyed" state and eventually gets purged.

Closing this issue.

If you still have issue , please reopen.

**Closed by sangeethah** 2015-06-08 17:21 UTC
Labels: area/container, bug, status/to-test
