### ISSUE TITLE
If no host/machine, multiple containers are continuously made by service 

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#639] opened 2015-04-29 17:58 UTC
v0.18.0
Steps:
1.  Delete all your hosts/machines
2.  Go to Service and create environment
3.  Create a Service with Scale set to 1
4.  Go to Container page

Results:
Service continuously creates container over and over again

Expected:
Service should recognize that there is no host to put container in, and should give user error message.

**Comment by alena1108** [comment] 2015-05-08 21:17
Duplicate of https://github.com/rancherio/rancher/issues/557. Service doesn't distinguish between the reason of containers failure; and it fails, the result is the same - service gets stuck in intermediate state and keeps on retrying to create a container. If we decide to change the way we handle failures, it would be the same fix for these 2 bugs.

**Closed by alena1108** 2015-05-08 21:17 UTC
Labels: area/service, bug
