### ISSUE TITLE
Support RHEL/CentOS 7

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#5] opened 2014-11-17 03:15 UTC
Because RHEL and its derivatives often lag behind on the version of Docker bundled, special consideration must be given to these distributions to support them.

**Comment by clemenko** [comment] 2015-04-09 12:14
Have you seen a problem with the rancher agent not being able to run on Centos 7?

[root@rancher1 ~]# docker logs -f d474de410265aa375d467d1587f4666dcd2190c9ac492d2a122f233e99e66267
time="2015-04-09T12:08:25Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" 
Please ensure Host Docker version is >= 1.4.1 and container has r/w permissions to docker.sock
[root@rancher1 ~]# docker -v
Docker version 1.5.0-dev, build fc0329b/1.5.0

I just pulled the latest rancher server and that works. Then using the custom add host script of 

docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://192.241.X.X:8080/v1/scripts/10549550552F5F944EA1:1428580800000:rs6uf8YRy8wSWXCTWH850HZV8c

Thoughts?

**Comment by ibuildthecloud** [comment] 2015-04-10 20:57
I figured this one out the other day.  We need to patch the rancher/agent to work around this.  The issue is totally odd.

/var/run is a symlink to /run in the agent container and bind mounting to /var/run/docker.sock ends up creating an empty file.  I have no clue why this only happens on RHEL but RHEL does maintain custom patches for Docker.

**Comment by clemenko** [comment] 2015-04-10 22:06
Is there a work around? I would love to see Rancher working on RHEL Atomic in my datacenter!

**Comment by clemenko** [comment] 2015-04-19 18:34
Is the patch applied yet?

**Comment by ibuildthecloud** [comment] 2015-04-19 18:51
We will get this in this Wednesday in the rancher/server:beta build.

Fyi @cloudnautique

**Comment by deniseschannon** [comment] 2015-04-29 18:57
@cloudnautique I am unable to test this out. Could you?

**Comment by deniseschannon** [comment] 2015-05-12 18:56
Here's an update on testing CentOS7. 

In CentOS7, Rancher server is broken with Docker 1.6.1. I cannot start Rancher server with either v0.20.0 or v0.18.2. Bug #778. 

With v0.18.2 and docker 1.5, Rancher Server works. I am able to launch hosts and spin up containers. If the hosts are ubuntu, my containers are launched and can ping each other. if the hosts are in CentOS, the containers are launched but are not part of the managed network and cannot ping each other or other containers on my ubuntu hosts. Similar to issue #725.

The issue with the CentOS hosts is also present in v0.20.0

**Comment by deniseschannon** [comment] 2015-05-14 20:48
Update: Docker's released version of 1.6.2 allowsRancher Server version v0.20.1 to be launched. I am able to launch hosts and containers. 

Still having issues with pinging containers between centos hosts, but between DO hosts, pinging works.

**Comment by clemenko** [comment] 2015-05-18 13:22
I can confirm v0.20.4 works with docker 1.6.2. HOWEVER docker 1.6.0 is centos 7 extras channel. Where can I find the rpms for docker 1.6.2?

**Comment by deniseschannon** [comment] 2015-05-18 16:51
@clemenko I'm not sure where to find it, but have you tried following the directions from this page: https://docs.docker.com/installation/centos/#manual-installation-of-latest-docker-release It talks about how to get the latest version if it's not included as part of package.

**Comment by clemenko** [comment] 2015-05-18 16:55
I followed docker's install and it works.

**Comment by ashish235** [comment] 2015-05-27 09:37
So what is it? Finally this is working for CentOS 7? I 'm still having issues. Can someone provide a short summary of any workaround if available. 

INFO: Running Agent Registration Process, CATTLE_URL=
INFO[8421] -job logs(c84a99bb128b) = OK (0)
time="2015-05-27T09:34:17Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"
INFO: Checking for Docker version >= 1.5.0
Please ensure Host Docker version is >= 1.5.0 and container has r/w permissions to docker.sock

**Comment by clemenko** [comment] 2015-05-27 10:40
@ashish235 Basically the current version of Docker that comes in the Extras channel is not named correctly. The easy fix is to get the binary straight from Docker. 
curl -s https://get.docker.com/builds/Linux/x86_64/docker-latest -o /usr/bin/docker
then restart docker. 
this works for me.

**Comment by ashish235** [comment] 2015-05-29 11:18
@clemenko, thanks. It worked for me as well. Cheers!

**Comment by will-chan** [comment] 2015-06-04 00:10
@deniseschannon can we close this?

**Comment by deniseschannon** [comment] 2015-06-04 00:29
@will-chan: this depends on what your definition of support is. we support the latest version of docker on rhel/centos 7, which requires a binary installation of the latest docker. rhel/centos 7 comes with docker 1.6.0, which hasn't been fully tested. i know that docker 1.6.1 doesn't work, so not sure if 1.6.0 would work.

**Comment by will-chan** [comment] 2015-06-04 01:04
For now, that's how I would define it.  Maybe we can create a separate issue for RHEL support + whatever docker version comes pre-installed to track it separately.  Not sure if that is a requirement right now.

**Comment by deniseschannon** [comment] 2015-06-04 05:22
Open #1034 for if/when we will support the pre-installed version of Docker with CentOS/RHEL 7.

**Closed by deniseschannon** 2015-06-04 05:22 UTC
Labels: area/packaging, bug
