### ISSUE TITLE
[Container] Should you be able to restart/stop/start containers on an inactive host?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#295] opened 2015-03-23 21:55 UTC
Version: v0.12.0

If I deactivate my host, I am able to attempt to restart/stop/start/delete my containers. 

But if my host is "Inactive", should these options be available? They don't work until the host is back in an "Active" state.

**Comment by vincent99** [comment] 2015-03-23 22:40
Theory: `inactive` means that you no new containers will be scheduled to that host.  stop/start/restart, etc of existing containers still works.  The UI should disable the Add container button on this host.  `reconnecting` means we do not have a connection open to the host, and any actions you do will not work.  It is debatable if the UI should continue to let you click on things for disconnected hosts, though those actions will happen when it reconnects.

Reality: `inactive` is currently preventing anything on the host from working.  This should be fixed in the backend.  And the UI doesn't stop you from attempting to add containers to it, that should be fixed in the UI.  @deniseschannon Do you want to split this up into 2 bugs?

**Comment by vincent99** [comment] 2015-03-31 19:25
Duplicate of #224

**Closed by vincent99** 2015-03-31 19:25 UTC
Labels: bug
