### ISSUE TITLE
Scale should not be available in Service details page when set to Global

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1037] opened 2015-06-04 07:26 UTC
v0.23.0-master
Steps:
1.  Make sure you have a couple of host
2.  Add Service
3.  Select Always run one instance of this container on every host
4.  Create Service
5.  Start Service
6.  Click on Service name to get to details page

Results:
The details page has the scale option available.  If I add or remove scale the service just continuously spins.

Expected
Scale should not be available for Global Service

**Comment by sangeethah** [comment] 2015-06-04 14:53
Duplicate of #1008

**Closed by sangeethah** 2015-06-04 14:53 UTC
Labels: area/service, area/ui, bug
